// Auto-generated by publish.ps1
// Last refreshed: 28-Apr-2026 20:20

var tasks = [
  {id:'QLI-SEC-01',name:'Semgrep scan on non kernel QC hosted public projects',cat:'Scanning/Tooling',owner:'Neeraj/Mark/Vishal and Ranjana',rel:'2',eta:'01-Jun-2026',revEta:'',status:'In Progress',rag:'Green',pct:50,risk:'',nextStep:'',updated:'11-Mar-2026'},
  {id:'QLI-SEC-02',name:'Smatch scan on Qcom next kernel PR',cat:'Scanning/Tooling',owner:'Vishal kumar and Madhukar',rel:'2.1',eta:'01-Sep-2026',revEta:'',status:'In Progress',rag:'Green',pct:50,risk:'Smatch needs compilation as per Madhukar',nextStep:'',updated:'11-Mar-2026'},
  {id:'QLI-SEC-03',name:'CVE Scan on Non kernel QC hosted projects (PR Review)',cat:'Scanning/Tooling',owner:'Abhijit, Sameesh and Kiron',rel:'2.1',eta:'01-Sep-2026',revEta:'',status:'In scoping',rag:'Green',pct:10,risk:'',nextStep:'',updated:'11-Mar-2026'},
  {id:'QLI-SEC-04',name:'CVE Scan on Qcom next kernel project (PR Review)',cat:'Scanning/Tooling',owner:'Abhijit, Sameesh and Kiron',rel:'2.1',eta:'01-Sep-2026',revEta:'',status:'In scoping',rag:'Green',pct:10,risk:'',nextStep:'',updated:'11-Mar-2026'},
  {id:'QLI-SEC-05',name:'Monthly CVE Scan on QLI 2.0 project',cat:'Scanning/Tooling',owner:'Abhijit and Kiron',rel:'2.2',eta:'01-Dec-2026',revEta:'',status:'Not Started',rag:'Green',pct:0,risk:'Resource concerns in QTVMS team to support QLI integration',nextStep:'',updated:'11-Mar-2026'},
  {id:'QLI-SEC-06',name:'Blakclisting on proprietary code (HLOS + NHLOS)',cat:'General',owner:'Srikanth,Sayan and Vishal',rel:'2.1',eta:'01-Sep-2026',revEta:'',status:'In Progress',rag:'Green',pct:50,risk:'AU labelling required for Blacklisting. Depends on QSWAT team for enabling AU labels for QLI builds',nextStep:'',updated:'11-Mar-2026'},
  {id:'QLI-SEC-07',name:'Weekly Klockworks scan on QLI mainline',cat:'Scanning/Tooling',owner:'Madhukar and Vishal',rel:'2.1',eta:'01-Sep-2026',revEta:'',status:'In Progress',rag:'Green',pct:50,risk:'',nextStep:'',updated:'11-Mar-2026'},
  {id:'QLI-SEC-11',name:'Dependency confusion scanner for OSS tools managed under Qualcomm and Qualcomm linux (PR review)',cat:'Scanning/Tooling',owner:'Sriram and Neeraj',rel:'2.2',eta:'01-Dec-2026',revEta:'',status:'In scoping',rag:'Green',pct:10,risk:'Dependency confusion scanner needs to make it public. Its internal now',nextStep:'',updated:'11-Mar-2026'},
  {id:'QLI-SEC-12',name:'Central dashboard for security governance',cat:'Governance',owner:'Thomas/mark and Ranjana',rel:'2.1',eta:'01-Sep-2026',revEta:'',status:'In scoping',rag:'Green',pct:10,risk:'No Dashboard and governance exist today for OSS security',nextStep:'',updated:'11-Mar-2026'},
  {id:'QLI-SEC-13',name:'Security Training',cat:'Training',owner:'Ranjana and Sameesh',rel:'2',eta:'01-Jun-2026',revEta:'',status:'In scoping',rag:'Green',pct:10,risk:'',nextStep:'',updated:'11-Mar-2026'},
  {id:'QLI-SEC-14',name:'Vulnerability management and exception workflow',cat:'Process/Compliance',owner:'Sameesh and Ranjana',rel:'2',eta:'01-Jun-2026',revEta:'',status:'In Progress',rag:'Green',pct:50,risk:'Resource concerns in QPSI VM for vulnerability management',nextStep:'',updated:'11-Mar-2026'},
  {id:'QLI',name:'QLI component scanning and blocking of open CRs',cat:'Scanning/Tooling',owner:'Sayan/Ramana/Shivang',rel:'2.1',eta:'01-Sep-2026',revEta:'',status:'In Progress',rag:'Green',pct:50,risk:'',nextStep:'',updated:'27-Apr-26'}
];

var backlog = [
  {id:'QLI-SEC-08',name:'Blacklisting for QC managed OSS project in Github',cat:'General',owner:'Srikanth',scope:'Need to scope',risk:'No BL support for Github projects. Need to develop the capabilty from scratch',updated:'11-Mar-2026'},
  {id:'QLI-SEC-09',name:'Add new semgrep rules for PR review',cat:'Scanning/Tooling',owner:'Madhukar',scope:'Need to scope',risk:'',updated:'11-Mar-2026'},
  {id:'QLI-SEC-10',name:'3rd party Dependency Management for OSS tools',cat:'Scanning/Tooling',owner:'Igibek and Neeraj',scope:'Need to scope',risk:'Dependabot creates lot of noise in report and we need to come up with a solution to reduce noise. Need prototyping',updated:'11-Mar-2026'},
  {id:'QLI-SEC-15',name:'Exapnding OSS CVE management into other linux distribution supported by QLI (Ubuntu, Fedora, centOS etc)',cat:'Scanning/Tooling',owner:'Sameesh',scope:'Not planned',risk:'Resource concerns in QPSI VM for mannaging multiple distributions. Scope is big',updated:'11-Mar-2026'},
  {id:'QLI-SEC-16',name:'Vulnerabilty management CRA compliance',cat:'Process/Compliance',owner:'Sameesh and Ranjana',scope:'Not planned',risk:'Working with PDms.Requiements are not yet clear as per Pdms.Pdms working with legal to get a clarity',updated:'11-Mar-2026'}
];

var releaseSummary = [
  {rel:'2',total:3,completed:0,inProgress:2,blocked:0,notStarted:0,inScoping:1,onHold:0,avgPct:37},
  {rel:'2.1',total:7,completed:0,inProgress:4,blocked:0,notStarted:0,inScoping:3,onHold:0,avgPct:33},
  {rel:'2.2',total:2,completed:0,inProgress:0,blocked:0,notStarted:1,inScoping:1,onHold:0,avgPct:5},
  {rel:'TBD',total:0,completed:0,inProgress:0,blocked:0,notStarted:0,inScoping:0,onHold:0,avgPct:0}
];

var lastRefreshed = '28-Apr-2026 20:20';
