# ============================================================
# QLI Security Dashboard - GitHub Pages One-Time Setup
# Run this ONCE to connect your dashboard to GitHub Pages
# ============================================================

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  QLI Security Dashboard - GitHub Setup" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# Check if git is installed
try {
    $gitVersion = git --version 2>&1
    Write-Host "[OK] Git found: $gitVersion" -ForegroundColor Green
} catch {
    Write-Host "[ERROR] Git is not installed." -ForegroundColor Red
    Write-Host "  Download from: https://git-scm.com/download/win" -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}

$dashboardPath = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $dashboardPath

Write-Host ""
Write-Host "Dashboard folder: $dashboardPath" -ForegroundColor Gray
Write-Host ""

# ---- Get GitHub details ----
Write-Host "Enter your GitHub details:" -ForegroundColor Cyan
Write-Host "(Create a free account at https://github.com if you don't have one)" -ForegroundColor Gray
Write-Host ""
$githubUsername = Read-Host "  GitHub username"
$repoName       = Read-Host "  Repository name (e.g., QLI-Security-Dashboard)"
Write-Host ""
$visibility = Read-Host "  Repository visibility? [public/private] (default: private)"
if ($visibility -ne "public") { $visibility = "private" }

$remoteUrl  = "https://github.com/$githubUsername/$repoName.git"
$pagesUrl   = "https://$githubUsername.github.io/$repoName/"

# ---- Initialize git repo ----
if (-not (Test-Path ".git")) {
    git init -b main 2>&1 | Out-Null
    Write-Host "[OK] Git repository initialized." -ForegroundColor Green
} else {
    Write-Host "[OK] Git repository already exists." -ForegroundColor Yellow
}

# ---- Create .gitignore ----
$gitignoreContent = @"
# Excel source files (stay local, never published)
*.xlsx
*.xls
*.xlsm

# OS files
.DS_Store
Thumbs.db
desktop.ini

# PowerShell temp
*.tmp
*.log
"@
$gitignoreContent | Out-File -FilePath ".gitignore" -Encoding UTF8
Write-Host "[OK] .gitignore created (Excel files will NOT be published)." -ForegroundColor Green

# ---- Set remote ----
$existingRemote = git remote get-url origin 2>&1
if ($LASTEXITCODE -eq 0) {
    git remote set-url origin $remoteUrl
    Write-Host "[OK] Remote URL updated to: $remoteUrl" -ForegroundColor Green
} else {
    git remote add origin $remoteUrl
    Write-Host "[OK] Remote origin set to: $remoteUrl" -ForegroundColor Green
}

# ---- Initial commit ----
git add index.html data.js refresh-data.ps1 publish.ps1 setup-github-pages.ps1 .gitignore 2>&1 | Out-Null
git commit -m "Initial commit: QLI Security Dashboard" 2>&1 | Out-Null
Write-Host "[OK] Initial commit created." -ForegroundColor Green

# ---- Print next steps ----
Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  NEXT STEPS (do these once in GitHub)" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "STEP 1 - Create the GitHub repository:" -ForegroundColor White
Write-Host "  Open: https://github.com/new" -ForegroundColor Yellow
Write-Host "  Name: $repoName" -ForegroundColor Yellow
Write-Host "  Visibility: $visibility" -ForegroundColor Yellow
Write-Host "  Do NOT initialize with README (leave empty)" -ForegroundColor Yellow
Write-Host ""
Write-Host "STEP 2 - Push your dashboard to GitHub:" -ForegroundColor White
Write-Host "  Run this command in PowerShell:" -ForegroundColor Gray
Write-Host "  git -C `"$dashboardPath`" push -u origin main" -ForegroundColor Yellow
Write-Host ""
Write-Host "STEP 3 - Enable GitHub Pages:" -ForegroundColor White
Write-Host "  Open: https://github.com/$githubUsername/$repoName/settings/pages" -ForegroundColor Yellow
Write-Host "  Source: Deploy from a branch" -ForegroundColor Yellow
Write-Host "  Branch: main   Folder: / (root)" -ForegroundColor Yellow
Write-Host "  Click Save" -ForegroundColor Yellow
Write-Host ""
Write-Host "STEP 4 - Your shareable dashboard URL:" -ForegroundColor White
Write-Host "  $pagesUrl" -ForegroundColor Green
Write-Host ""
Write-Host "STEP 5 - To publish updates in the future, just run:" -ForegroundColor White
Write-Host "  publish.ps1" -ForegroundColor Yellow
Write-Host ""
Write-Host "NOTE: GitHub Pages for private repos requires GitHub Pro/Team." -ForegroundColor Gray
Write-Host "      For a free account, set the repo to 'public'." -ForegroundColor Gray
Write-Host ""

# Save the config for publish.ps1 to use
$config = @"
# Auto-generated by setup-github-pages.ps1
`$githubUsername = '$githubUsername'
`$repoName = '$repoName'
`$pagesUrl = '$pagesUrl'
"@
$config | Out-File -FilePath ".github-config.ps1" -Encoding UTF8

Read-Host "Press Enter to exit"
